server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # --- TEAM SERVICE MUSI BYĆ PIERWSZY (bo ma bardziej szczegółową ścieżkę) ---
        - id: team-service
          # Pamiętaj, żeby tu było http://team-service:8082 (nazwa z dockera), a nie localhost
          uri: ${TEAM_URI:http://team-service:8082}
          predicates:
            - Path=/leagues/*/teams/**, /leagues/*/teams, /teams/**

        # --- LEAGUE SERVICE DRUGI (Catch-all dla lig) ---
        - id: league-service
          uri: ${LEAGUE_URI:http://league-service:8081}
          predicates:
            - Path=/leagues/**