server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: team-service
          uri: http://localhost:8082
          predicates:
            - Path=/leagues/*/teams/**, /leagues/*/teams

        - id: league-service
          uri: http://localhost:8081
          predicates:
            - Path=/leagues/**